# Generated by Django 4.0.6 on 2022-08-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='RegistrationTime',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
